version: '3.1'

services:
  web:
    build: .
    depends_on:
      - postgres
    volumes:
      - ./:/code:ro
    ports:
      - "9000:9000"

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
      postgres_data: 